### ISSUE TITLE
Rely libreadline6-dev on Ubuntu

### ISSUE THREAD

**Issue by ethe** [greyblake/crystal-icr#11]
```shell
/usr/bin/ld: cannot find -lreadline
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "cli" "${@}"  -rdynamic  -lcrypto -lreadline /opt/crystal/src/ext/libcrystal.a -levent -lrt -lpcre -lgc -lpthread -ldl`
```

I think README should point out it.

**Comment by greyblake** [comment]
Thanks, for the report) Updated README 3d8cc20

**Comment by ethe** [comment]
Crystal compiler will create a `.crystal` folder at current path if run .cr file directly, so if I use icr several times, the`.crystal` folder would exists in everywhere. I think icr should clean it when exit.

**Comment by greyblake** [comment]
@ethe Heh! I got this notification by email. and long time could not figure it out where it was)
It's better to have a separate issue for this, I've just created it: https://github.com/greyblake/crystal-icr/issues/14
