### ISSUE TITLE
Assignment with operators error

### ISSUE THREAD

**Issue by AlexWayfer** [greyblake/crystal-icr#12]
```crystal
icr(0.12.0) > a = 2
 => 2
icr(0.12.0) > a *= 3
'*=' before definition of 'a'
```
[Docs](http://crystal-lang.org/docs/syntax_and_semantics/assignment.html)

**Comment by greyblake** [comment]
Wow)) You are good at detecting new bugs!
Thanks for the report. I guess it cannot parse line `a *= 3`, because crystal parser thinks variable `a` is not declared yet. I'll think what we can do about it)

**Comment by greyblake** [comment]
Fixed in https://github.com/greyblake/crystal-icr/commit/0787f214cad9e5230a12c73ae6a8bbd1bf25ba37

See v0.2.6
