### ISSUE TITLE
Cleanup .crystal dir on exit

### ISSUE THREAD

**Issue by greyblake** [greyblake/crystal-icr#14]
https://github.com/greyblake/crystal-icr/issues/11#issuecomment-187034977

**Comment by BlaXpirit** [comment]
Users who don't want `.crystal` folders everywhere can set
```bash
CRYSTAL_CACHE_DIR="/tmp/crystal_cache"
```

/cc @ethe

**Comment by greyblake** [comment]
@BlaXpirit Thanks for the nice trick. Anyway I've just fixed it, https://github.com/greyblake/crystal-icr/commit/7faddfe9ea075a31e02b71d369a0c7004dd05344.

It will remove only own tmp files, and if there is nothing left, then remove `.crystal` dir completely.

**Comment by ethe** [comment]
:+1:
