### ISSUE TITLE
Unable to define records in icr

### ISSUE THREAD

**Issue by puppetpies** [greyblake/crystal-icr#23]
icr(0.18.6) > record Person, first_name : String, last_name : String do
icr(0.18.6) >     
icr(0.18.6) >     def full_name
icr(0.18.6) >       "#{first_name} #{last_name}"
icr(0.18.6) >     end
icr(0.18.6) >     
icr(0.18.6) >   end
Syntax error in ./.icr_yNuX8BhwZzkOz4suZmFkSA.cr:4: can't define def inside def

  def full_name
  ^
icr(0.18.6) > 
icr(0.18.6) > a = Person.new("Mike", "Nog")
Error in ./.icr_yNuX8BhwZzkOz4suZmFkSA.cr:5: instantiating '__icr_exec__()'

puts "|||YIH22hSkVQN|||#{__icr_exec__.inspect}"
                         ^~~~~~~~~~~~

in ./.icr_yNuX8BhwZzkOz4suZmFkSA.cr:2: undefined constant Person

  a = Person.new("Mike", "Nog")
      ^~~~~~

**Comment by greyblake** [comment]
Yea, ICR is not aware about `record` yet. Thanks for the report!

**Comment by puppetpies** [comment]
I'll close this now !

**Comment by greyblake** [comment]
Thanks!
