### ISSUE TITLE
unexpected token error

### ISSUE THREAD

**Issue by jwoertink** [greyblake/crystal-icr#26]
This small snippet comes from one of the [crystal samples](https://github.com/crystal-lang/crystal/blob/master/samples/2048.cr#L7). 

``` text
icr(0.19.1) > module Screen
icr(0.19.1) >   TILES = {
icr(0.19.1) >           0 => {:white, nil},
unterminated hash literal
icr(0.19.1) > 2 => {:black, :white},
unexpected token: =>
icr(0.19.1) > }
icr(0.19.1) >   end
```

These errors prevent you from pasting any more of the example in.

**Comment by greyblake** [comment]
Thanks for the report!

**Comment by greyblake** [comment]
This is gonna be tricky to fix. ICR is not very good at handling multiline input.. We're relying on `Crystal::Parser` that comes from Crystal's source code.. But it's not always clear how to determine one of the two possible options: whether user already finished the input and it's invalid or user is gonna continue to enter something :(

**Comment by jwoertink** [comment]
Yeah, I figured it wouldn't be easy. I'll take a stab at a PR, just might take me a little extra time :)

**Comment by greyblake** [comment]
Hi! That sounds good) Sorry, likeky I'll be able to take close look only in
2 weeks, cause I am getting married in few days, and there are so many
things to do)

But anyway thanks for the feedback, I'll definitly will take a look!)

**Comment by jwoertink** [comment]
nice! Congrats on the wedding. Seems to be wedding season around here.
