### ISSUE TITLE
API for library to show object's summary

### ISSUE THREAD

**Issue by dylandy** [greyblake/crystal-icr#37]
I wonder if there could be any APIs for library to show summary for the object that it create.

For example in irb there are something like :

```ruby
001 > require "statsample"
     => true
002 > [1,2,3].to_vector
     => #<Daru::Vector(3)>
           0   1
           1   2
           2   3 
```

**Comment by greyblake** [comment]
Hey! It's responsibility of a particular library (in you case it's `statsample`).

You can implement your own library similar to that one, defining `inspect` methods on object.

ICR allows you to require external libraries: https://github.com/greyblake/crystal-icr#require-local-files

**Comment by dylandy** [comment]
Thanks a lot !
