### ISSUE TITLE
OS X El Capitan Errors

### ISSUE THREAD

**Issue by runeimp** [greyblake/crystal-icr#40]
I updated Crystal and just installed icr version 0.2.13 via Homebrew. And am getting an error in ICR

```
$ icr
icr(0.20.3) > 2 + 2
Error: unknown command: /Users/runeimp/Google
icr(0.20.3) >
```
Doesn't matter what I type I get the same error as a result.  😞

**Comment by jwoertink** [comment]
That's really weird. Can you try removing that version of ICR, and then install from github directly?

**Comment by runeimp** [comment]
Rebooted, Homebrew uninstalled, and Homebrew reinstalled. Happy now. No idea why it didn't install properly yesterday. I had happened to reboot shortly before installing at that time.  🦄

**Comment by jwoertink** [comment]
Ok, cool. Glad to see it's all fixed now! Report if there's any other issues 😄

**Comment by greyblake** [comment]
@jwoertink Thanks for helping to resolve the issue:)
