### ISSUE TITLE
Feature: Tab completion of methods, functions, and attributes of Classes, instances, or modules

### ISSUE THREAD

**Issue by elbow-jason** [greyblake/crystal-icr#42]
### Expected Behavior: 

If I am in the REPL and I have a string instance `x` I should be able to type `x.`, press the `Tab` key, and be shown the instance methods of `String`. If I type `x.to_` and press `Tab` I should see all the `String` instance methods that start with `to_`.

**Comment by jwoertink** [comment]
I have this sort of started, but the issue is that it will need the `Readline` library for this to work, but Readline doesn't work that well in macOS, so everything I've tried fails. Definitely something to add in though.

**Comment by greyblake** [comment]
I guess it's not possible to implement for `icr`. 
Icr has no idea about types and current context. 
It's not a proper REPL, rather it is a work around for REPL)

Sorry. I wish this feature too.
