### ISSUE TITLE
Empty inputs print the last value

### ISSUE THREAD

**Issue by bfontaine** [greyblake/crystal-icr#5]
Hello,

I’m not sure this is intentional. If you type, e.g. `2+2` it gives you `4` but if you press <kbd>enter</kbd> any number of times after that it’ll always give you `4`:

```
$ ./bin/icr
icr(0.11.0) > 2+2
 => 4
icr(0.11.0) >
 => 4
icr(0.11.0) >
 => 4
icr(0.11.0) >
 => 4
icr(0.11.0) >
```

This is the same if you press `^D`, which, in `irb` (and most REPLs), allows you to quit:

```
$ ./bin/icr
icr(0.11.0) > 2+2
 => 4
icr(0.11.0) > ^D => 4
icr(0.11.0) > ^D => 4
```

If you press <kbd>enter</kbd> at the very beginning you’ll get `nil` instead of the previous value.

**Comment by greyblake** [comment]
It's a bug, I am gonna fix it)

**Comment by greyblake** [comment]
Thanks for the report!

**Comment by greyblake** [comment]
@bfontaine Fixed in https://github.com/greyblake/crystal-icr/commit/7a3046c1a53ce9799719b29a8cf87700f3afe15d

**Comment by bfontaine** [comment]
Thanks for fixing this :smiley:
