### ISSUE TITLE
Make (build) error

### ISSUE THREAD

**Issue by AlexWayfer** [greyblake/crystal-icr#7]
```bash
~/Projects/crystal/crystal-icr $ uname -a
Linux AlexNote-Arch 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux

~/Projects/crystal/crystal-icr $ make
/usr/bin/crystal build --release -o bin/icr src/icr/cli.cr 
./.crystal/home/alex/Projects/crystal/crystal-icr/src/icr/cli.cr/_main.o: In function `__crystal_main':
main_module:(.text+0x50bd): undefined reference to `LLVMInitializeX86TargetInfo'
main_module:(.text+0x50c2): undefined reference to `LLVMInitializeX86Target'
main_module:(.text+0x50c7): undefined reference to `LLVMInitializeX86TargetMC'
main_module:(.text+0x50cc): undefined reference to `LLVMInitializeX86AsmPrinter'
main_module:(.text+0x50d1): undefined reference to `LLVMInitializeX86AsmParser'
main_module:(.text+0x50d6): undefined reference to `LLVMLinkInMCJIT'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "bin/icr" "${@}"  -rdynamic  `(llvm-config-3.6 --libs --system-libs --ldflags 2> /dev/null) || (llvm-config-3.5 --libs --system-libs --ldflags 2> /dev/null) || (llvm-config --libs --system-libs --ldflags 2>/dev/null)` -lstdc++ -lcrypto -lreadline -levent -lrt -lpcre -lgc -lpthread -ldl`
Makefile:5: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by greyblake** [comment]
@AlexWayfer Thanks for opening the issue! Currently TravisCI build fails the same way: https://travis-ci.org/greyblake/crystal-icr/jobs/106010534

Can you please provide information about llvm version? E.g.
```
llvm-link --version
```
Are you able to run other programs in Crystal?

**Comment by AlexWayfer** [comment]
```bash
~/Projects/crystal/test $ crystal -v
Crystal 0.11.1 (Mon Jan 25 18:48:32 UTC 2016)
~/Projects/crystal/test $ llvm-link --version
bash: llvm-link: command not found
~/Projects/crystal/test $ cat test.cr
puts "Hello, world!"
~/Projects/crystal/test $ crystal test.cr
Hello, world!
```

**Comment by marceloboeira** [comment]
@AlexWayfer it seems like your crystal was installed without llvm,

Have you installed with brew? If you did,  try to uninstall it and install with llvm:
`bre uninstall crystal-lang` -> to uninstall
`brew install crystal-lang --with-llvm` -> to make sure that llvm is present

**Comment by marceloboeira** [comment]
@greyblake I'm gonna make sure that crystal is installed with llvm on the brew package, so that kind of error don't became a problem when installing crystal-icr over brew.

**Comment by AlexWayfer** [comment]
No-no, i wrote about my system at the first comment: **Arch Linux**. Crystal from [core repository](https://www.archlinux.org/packages/community/x86_64/crystal/). Working good.

**Comment by marceloboeira** [comment]
@AlexWayfer Oh, sorry. 

But I guess that would also be also a problem for those who had installed over brew without llvm.

**Comment by AlexWayfer** [comment]
But Crystal works fine without llvm. Is it requirement for `crystal-icr`? Or why is it?

**Comment by greyblake** [comment]
@AlexWayfer I guess i've fixed this issue (at least specs at TravisCI now pass). Could you please checkout changes from master and try again?

**Comment by marceloboeira** [comment]
@AlexWayfer crystal is "complied" with `llvm` but after that there is no need for it.

**Comment by AlexWayfer** [comment]
@greyblake Yeah! It's working! Thanks.

**Comment by greyblake** [comment]
Cool!) 
@marceloboeira @AlexWayfer 
I order to validate "unexpected EOF" syntax error, I used to require  entire compiler (looks like there LLVM dependecies). Now I require only necessary minimum: https://github.com/greyblake/crystal-icr/commit/c3ff86ec797d1f513bf1ca224e039b95cbd684aa
