### ISSUE TITLE
Installation (and updating) on Arch Linux via AUR

### ISSUE THREAD

**Issue by AlexWayfer** [greyblake/crystal-icr#8]
It would be awesome to easily install it via AUR.
Checkout [Arch Wiki](https://wiki.archlinux.org/index.php/Arch_User_Repository#Sharing_and_maintaining_packages) for AUR packages, please.
[shards-git](https://aur.archlinux.org/packages/shards-git/), for example.

**Comment by greyblake** [comment]
Hi, thanks for opening this issue.
Unfortunately I am not Arch user (I am Debian guy) and likely I won't be able to dive into Arch in the nearest time. 
If you want, you can volunteer, pull request are always welcome)

**Comment by BlaXpirit** [comment]
https://aur.archlinux.org/packages/crystal-icr/

**Comment by AlexWayfer** [comment]
@BlaXpirit Thanks!

**Comment by greyblake** [comment]
Thanks @BlaXpirit !

**Comment by greyblake** [comment]
@AlexWayfer @BlaXpirit Hey, can you provide instructions how to install that package, I'll add it to README? (or you can open PR)
Thanks)

**Comment by BlaXpirit** [comment]
> Arch Linux users can install ICR [from AUR](https://aur.archlinux.org/packages/crystal-icr/).

&mdash; they'll know what to do. There are many ways to install from AUR, so detailed instructions are usually bad.

**Comment by greyblake** [comment]
@BlaXpirit Дякую! =)
